### PR TITLE
Fix flasher recovery for stm and esp chips

### LINKED ISSUE #263: Add serial flashing recovery mode

### LINKED ISSUE #334: Fix flasher recovery

### PR DESCRIPTION
**Pull request by BrettRegnier**
Closes #334 
Closes #263

### CODE REVIEW

File: firmware/mgmt/src/uart_router.c [hunk 1]
```diff
@@ -2,6 +2,14 @@
 #include "main.h"
 #include <string.h>
 
+// https://stackoverflow.com/questions/3437404/min-and-max-in-c
+#define min(a, b)                                                                                  \
```
Comment (GhostofCookie) [inline firmware/mgmt/src/uart_router.c]: Why not use `fmin` from `<math.h>` as that link recommends instead of using defines?

File: firmware/mgmt/src/uart_router.c [hunk 2]
```diff
@@ -226,23 +243,48 @@ void uart_router_rx_isr(uart_stream_t* stream, const uint16_t num_received)
...
+    // }
+
     // Copy bytes to tx buffer
-    tx->unsent += num_bytes;
+    // tx->unsent += num_bytes;
+
+    // if (tx->unsent > tx->size)
+    // {
+    //     tx->unsent = tx->size;
+    // }
```
Comment (GhostofCookie) [inline firmware/mgmt/src/uart_router.c]: Dead code alert.

File: firmware/mgmt/src/uart_router.c [hunk 3]
```diff
@@ -316,10 +353,23 @@ void uart_router_parse_internal(const command_map_t command_map[Cmd_Count])
         uart_router_send_string(&usb_uart, "[Error] command timeout\n");
     }
 
-    while (internal_tx.unsent > 0)
+    if (HAL_GetTick() - last_receive_tick >= 100 && internal_tx.read != internal_tx.write
```
Comment (GhostofCookie) [inline firmware/mgmt/src/uart_router.c]: Magic number?
